### ISSUE TITLE
organization todo list

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/2021-03-17-testing-hackathon#1]
- [x] recruit instructors
- [x] recruit helpers
- [ ] prepare material
- [x] decide dates
- [x] create event webpage
- [ ] create registration form with max-participants 50% over capacity 
- [ ] open registration
- [ ] advertise event
- [ ] close registration
- [ ] approve participants (assume 25% no-shows)
- [ ] inform people on waiting list
- [ ] (optional) ask invited participants to confirm attendance
- [ ] set up zoom link and hackMD doc
- [ ] (optional) schedule installation help zoom session
- [ ] send installation instructions 1-2 weeks before event. Request early cancellation
- [ ] invite from the waiting list in order of registration date
- [ ] (optional) organize helper training/coordination session
- [ ] set up post-workshop survey form
- [ ] after ws or on last day: send out post-workshop survey 
- [ ] after ws: debrief and analyze survey results
